DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    description TEXT,
    cover_url TEXT,
    year INTEGER,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    student_id TEXT NOT NULL,
    group_name TEXT NOT NULL,
    avatar_url TEXT,
    bio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- insert dummy data
INSERT INTO categories (name, image_url, description) VALUES
('Novel & Sastra', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=500&q=80', 'Koleksi novel best seller dan karya sastra klasik.'),
('Teknologi', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=500&q=80', 'Buku-buku seputar pemrograman, desain, dan teknologi terbaru.'),
('Sejarah', 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=500&q=80', 'Menelusuri jejak masa lalu lewat literasi sejarah.');

INSERT INTO books (title, author, year, description, cover_url, category_id) VALUES
('Laskar Pelangi', 'Andrea Hirata', 2005, 'Kisah perjuangan anak-anak Belitong dalam menuntut ilmu.', 'https://upload.wikimedia.org/wikipedia/id/8/8e/Laskar_pelangi_sampul.jpg', 1),
('Bumi Manusia', 'Pramoedya Ananta Toer', 1980, 'Roman sejarah pergerakan nasional di awal abad 20.', 'https://upload.wikimedia.org/wikipedia/id/4/44/Bumi_Manusia.jpg', 1),
('Cantik Itu Luka', 'Eka Kurniawan', 2002, 'Sebuah novel realisme magis tentang sejarah kelam masa kolonial.', 'https://upload.wikimedia.org/wikipedia/id/7/7e/Cantik_Itu_Luka.jpg', 1),

('Clean Code', 'Robert C. Martin', 2008, 'Panduan menulis kode yang bersih dan mudah dipelihara.', 'https://m.media-amazon.com/images/I/41xShlnTZTL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg', 2),
('The Pragmatic Programmer', 'Andrew Hunt', 1999, 'Tips praktis menjadi programmer yang handal.', 'https://m.media-amazon.com/images/I/51IA4hT6jrL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg', 2),

('Sapiens', 'Yuval Noah Harari', 2011, 'Riwayat singkat umat manusia dari zaman batu hingga modern.', 'https://m.media-amazon.com/images/I/41yu2qXhXXL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg', 3);

INSERT INTO profiles (full_name, student_id, group_name, avatar_url, bio) VALUES
('Muhammad Danial Irfani', '21120123130061', 'Kelompok 24', 'https://scontent-sin2-3.cdninstagram.com/v/t51.2885-19/431447005_920377696294015_6210779198628712534_n.jpg?efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby4xMDgwLmMyIn0&_nc_ht=scontent-sin2-3.cdninstagram.com&_nc_cat=107&_nc_oc=Q6cZ2QGtkbRCEeAzpwy9cz33ma-uJh_GHEMf4HJosFXvEEX-l10U5_JcGVeKJXWC2fuY5Ml1Z19ISgwNfNsqKiLXgyJQ&_nc_ohc=a9QcHH_BS-AQ7kNvwEim-dB&_nc_gid=quIJ2s3CFcC9hQHl0w10FA&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_Afj6GsBzgjTiJVjm_3QtaN2W-73NZx4SQLxhhcCAMFrKLA&oe=692967DE&_nc_sid=7a9f4b', 'Mahasiswa Teknik Komputerrrr');